version: '3.7'
services: 
    db:
        image: mysql:latest
        env_file: 
            - app/.env
        ports:
            - "3307:3306"
        volumes: 
            - dbvol:/var/lib/mysql
        networks:
            - backend
    api:
        build: ./app
        ports:
            - "8000:8000"
        depends_on: 
            - db
        networks: 
            - backend
            - frontend
    # client:
    #     build: ./client
    #     ports: 
    #         - "5000:80"
    #     depends_on: 
    #         - api
    #         - db
    #     networks:
    #         - frontend
volumes: 
    dbvol:
networks:
    backend:
    frontend: