version: '3.7'
services: 
    db:
        image: mysql:latest
        environment: 
            MYSQL_ROOT_PASSWORD: 123
        ports: 
            - "3307:3306"
        volumes: 
            - dbvol:/var/lib/mysql
        networks:
            - backend
    # api:
    #     build: ./app
    #     ports:
    #         - "8000:8000"
    #     depends_on: 
    #         - db
    #     networks: 
    #         - backend
    #         - frontend

volumes: 
    dbvol:
networks:
    backend:
    frontend: