version: '3.7'
services: 
    db:
        image: mysql:latest
        env_file: 
            - app/.env
        volumes: 
            - dbvol:/var/lib/mysql
        ports:
            - 3307:3306
        networks:
            - backend
    api:
        build: ./app
        ports:
            - "8000:8000"
        depends_on: 
            - db
        networks: 
            - backend
volumes: 
    dbvol:
networks:
    backend: