version: '3.7'
services: 
    db:
        image: mysql:latest
        environment: 
            MYSQL_ROOT_PASSWORD: 123
        ports: 
            - "3307:3306"
        volumes: 
            - dbvol:/var/lib/mysql
volumes: 
    dbvol: